# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Setup
title:            Farah Baracat
tagline:          'A Jekyll theme'
description:      'I am a first year PhD student at  the Institute of Neuroinformatics UZH, Switzerland, in the Neuromorphic Cognitive Systems group '
url:              https://farahbaracat.com #http://hyde.getpoole.com
baseurl:          ""

author:
  name:           'Farah Baracat'
  url:            https://twitter.com/farahbaracat

paginate:
paginate_path:    blog/page:num/

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
